FreeLing: freeling::check_pos Class Reference
freeling::check_pos Class Reference
match pos against regexp
#include <dep_rules.h>
Public Member Functions
check_pos (const std::wstring &, const std::wstring &)
check head PoS
bool eval (dep_tree::iterator) const
eval whether a single node matches a condition only called from check if needed.
Detailed Description
match pos against regexp
Constructor & Destructor Documentation
freeling::check_pos::check_pos (const std::wstring & , const std::wstring &)
check head PoS
Member Function Documentation
bool freeling::check_pos::eval (dep_tree::iterator n) const [virtual]
eval whether a single node matches a condition only called from check if needed.
The abstract class version should never be reached.
Reimplemented from freeling::rule_expression.
References freeling::word::get_tag(), freeling::node::get_word(), freeling::rule_expression::match(), and TRACE.
The documentation for this class was generated from the following files:
dep_rules.h
dep_rules.cc