FreeLing: freeling::dataset Class Reference
freeling::dataset Class Reference
Class dataset stores a set of examples uset to train adaboost models.
#include <dataset.h>
Classes
class const_iterator
class iterator
Public Member Functions
dataset (int nlabels)
void add_example (const example &)
input
int get_negative_size (int l) const
consultors
int get_positive_size (int l) const
int get_nlabels () const
int get_dimension () const
void split (int feature, dataset &ds0, dataset &ds1) const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
Private Member Functions
void add_member (std::list< example >::iterator)
Private Attributes
std::vector< int > size_pos
std::vector< int > size_neg
int dimension
int nlabels
Static Private Attributes
static std::list< example > all_examples
static list to store all examples from all datasets.
Detailed Description
Class dataset stores a set of examples uset to train adaboost models.
Constructor & Destructor Documentation
freeling::dataset::dataset (int nlabels)
Member Function Documentation
void freeling::dataset::add_example (const example &)
input
void freeling::dataset::add_member (std::list< example >::iterator) [private]
iterator freeling::dataset::begin () [inline]
Referenced by begin().
const_iterator freeling::dataset::begin () const [inline]
References begin().
iterator freeling::dataset::end () [inline]
Referenced by end().
const_iterator freeling::dataset::end () const [inline]
References end().
int freeling::dataset::get_dimension () const
int freeling::dataset::get_negative_size (int l) const
consultors
int freeling::dataset::get_nlabels () const
int freeling::dataset::get_positive_size (int l) const
void freeling::dataset::split (int feature, dataset & ds0, dataset & ds1) const
Member Data Documentation
std::list<example> freeling::dataset::all_examples [static, private]
static list to store all examples from all datasets.
thread unsafe, but it is only used in training.
int freeling::dataset::dimension [private]
int freeling::dataset::nlabels [private]
std::vector<int> freeling::dataset::size_neg [private]
std::vector<int> freeling::dataset::size_pos [private]
The documentation for this class was generated from the following file:
dataset.h