FreeLing: freeling::semanticDB Class Reference
freeling::semanticDB Class Reference
Class semanticDB implements a semantic DB interface.
#include <semdb.h>
Public Member Functions
semanticDB (const std::wstring &)
Constructor.
~semanticDB ()
Destructor.
void get_WN_keys (const std::wstring &, const std::wstring &, const std::wstring &, std::list< std::pair< std::wstring, std::wstring > > &) const
Compute list of lemma-pos to search in WN for given word, according to mapping rules.
std::list< std::wstring > get_sense_words (const std::wstring &) const
get list of words for a sense
std::list< std::wstring > get_word_senses (const std::wstring &, const std::wstring &, const std::wstring &) const
get list of senses for a lemma+pos
sense_info get_sense_info (const std::wstring &) const
get sense info for a sense
Private Attributes
std::list< posmaprule > posmap
map of PoS tags to WN lemma+postag
database * form_dict
map of (lema,pos) -> form
database * sensesdb
actual storage
database * wndb
Detailed Description
Class semanticDB implements a semantic DB interface.
Constructor & Destructor Documentation
freeling::semanticDB::semanticDB (const std::wstring & wsdFile)
Constructor.
Create the sense annotator.
References freeling::config_file::add_section(), freeling::config_file::close(), DB_MAP, ERROR_CRASH, freeling::config_file::get_content_line(), freeling::config_file::get_section(), freeling::posmaprule::lemma, freeling::config_file::open(), freeling::posmaprule::pos, and freeling::posmaprule::wnpos.
freeling::semanticDB::~semanticDB ()
Destructor.
Destroy sense annotator module, close database.
Member Function Documentation
sense_info freeling::semanticDB::get_sense_info (const std::wstring &) const
get sense info for a sense
Get info for a sense+pos.
access DB and split obtained data_string into fields and store appropriately in a sense_info object
add also list of synset words
References freeling::sense_info::words.
Referenced by freeling::check_tonto::eval(), freeling::check_semfile::eval(), freeling::check_synon::eval(), and freeling::check_asynon::eval().
list< wstring > freeling::semanticDB::get_sense_words (const std::wstring &) const
get list of words for a sense
Get synonyms for a sense+pos.
References wstring2list.
void freeling::semanticDB::get_WN_keys (const std::wstring & , const std::wstring & , const std::wstring & , std::list< std::pair< std::wstring, std::wstring > > &) const
Compute list of lemma-pos to search in WN for given word, according to mapping rules.
Compute list of lemma-pos to search in WN for given word and analysis, according to mapping rules.
References TRACE, and wstring2list.
list< wstring > freeling::semanticDB::get_word_senses (const std::wstring & , const std::wstring & , const std::wstring &) const
get list of senses for a lemma+pos
Get senses for a lemma+pos.
References list2wstring, TRACE, and wstring2list.
Referenced by freeling::check_tonto::eval(), freeling::check_semfile::eval(), freeling::check_synon::eval(), and freeling::check_asynon::eval().
Member Data Documentation
database* freeling::semanticDB::form_dict [private]
map of (lema,pos) -> form
std::list<posmaprule> freeling::semanticDB::posmap [private]
map of PoS tags to WN lemma+postag
database* freeling::semanticDB::sensesdb [private]
actual storage
database* freeling::semanticDB::wndb [private]
The documentation for this class was generated from the following files:
semdb.h
semdb.cc