FreeLing: freeling::POS_tagger Class Reference
freeling::POS_tagger Class Reference
The class POS_tagger is just an abstract class generalizing a PoS tagger.
#include <tagger.h>
Public Member Functions
POS_tagger (bool, unsigned int)
Create an instance of the class, initializing options member.
virtual ~POS_tagger ()
virtual void annotate (sentence &) const =0
Do actual disambiguation.
void analyze (sentence &) const
analyze given sentence
Protected Member Functions
void retokenize (sentence &) const
Look for words whose selected tag has retokenizing rules, and retokenize them appropriately.
void force_select (sentence &) const
Look for words with remaining ambiguity and force the selection of only one Pos tag.
Protected Attributes
bool retok
unsigned int force
Detailed Description
The class POS_tagger is just an abstract class generalizing a PoS tagger.
Constructor & Destructor Documentation
freeling::POS_tagger::POS_tagger (bool r, unsigned int f)
Create an instance of the class, initializing options member.
Since tagger is an abstract class, this is called always from child constructors.
virtual freeling::POS_tagger::~POS_tagger () [inline, virtual]
Member Function Documentation
void freeling::POS_tagger::analyze (sentence & s) const [virtual]
analyze given sentence
Disambiguate all words in given sentence.
Implements freeling::processor.
References annotate(), ERROR_CRASH, force, FORCE_RETOK, force_select(), FORCE_TAGGER, retok, and retokenize().
virtual void freeling::POS_tagger::annotate (sentence &) const [pure virtual]
Do actual disambiguation.
Implemented in freeling::hmm_tagger, and freeling::relax_tagger.
Referenced by analyze().
void freeling::POS_tagger::force_select (sentence & se) const [protected]
Look for words with remaining ambiguity and force the selection of only one Pos tag.
References TRACE, and TRACE_SENTENCE.
Referenced by analyze().
void freeling::POS_tagger::retokenize (sentence & se) const [protected]
Look for words whose selected tag has retokenizing rules, and retokenize them appropriately.
References int2wstring, freeling::sentence::rebuild_word_index(), TRACE, and TRACE_SENTENCE.
Referenced by analyze().
Member Data Documentation
unsigned int freeling::POS_tagger::force [protected]
Referenced by analyze().
bool freeling::POS_tagger::retok [protected]
Referenced by analyze().
The documentation for this class was generated from the following files:
tagger.h
tagger.cc