FreeLing: freeling::RE_map Class Reference
freeling::RE_map Class Reference
Class tag_map implements a mapping from a regexps to an associated data string.
#include <RE_map.h>
Public Member Functions
RE_map (const std::wstring &)
Constructor.
void annotate_word (word &) const
annotate given word
void analyze (sentence &) const
analyze given sentence
Private Attributes
std::list< RE_map_rule > regexps
list of regex with associated information
Detailed Description
Class tag_map implements a mapping from a regexps to an associated data string.
Regexps are sequentially checked until a match is found. This module allows the user application to directly assign tags to certain words or patterns.
Constructor & Destructor Documentation
freeling::RE_map::RE_map (const std::wstring & puntFile)
Constructor.
Create a RegExp mapping module.
References ERROR_CRASH, and TRACE.
Member Function Documentation
void freeling::RE_map::analyze (sentence & se) const [virtual]
analyze given sentence
Check words in given sentence for regexp matches.
Implements freeling::processor.
Referenced by freeling::maco::analyze().
void freeling::RE_map::annotate_word (word & w) const
annotate given word
Check given word for regexp matches.
References freeling::word::add_analysis(), freeling::word::get_form(), freeling::word::lock_analysis(), and TRACE.
Member Data Documentation
std::list<RE_map_rule> freeling::RE_map::regexps [private]
list of regex with associated information
The documentation for this class was generated from the following files:
RE_map.h
RE_map.cc