FreeLing: freeling::regexp Class Reference
freeling::regexp Class Reference
#include <regexp.h>
Public Member Functions
regexp (const regexp &)
Copy constructor.
regexp (const std::wstring &expr, bool icase=false)
~regexp ()
Destructor.
bool search (const std::wstring &in, bool continuous=false) const
Search for a partial match in a string.
bool search (const std::wstring &in, std::vector< std::wstring > &out, bool continuous=false) const
Search for a partial match in a string, return sub matches.
bool search (const std::wstring &in, std::vector< std::wstring > &out, std::vector< int > &pos, bool continuous=false) const
Search for a partial match in a string, return sub matches and positions.
bool search (std::wstring::const_iterator i1, std::wstring::const_iterator i2, std::vector< std::wstring > &out, bool continuous=false) const
Search for a partial match in a string, return sub matches.
bool search (std::wstring::const_iterator i1, std::wstring::const_iterator i2, std::vector< std::wstring > &out, std::vector< int > &pos, bool continuous=false) const
Search for a partial match in a string, return sub matches and positions.
bool match (const std::wstring &in) const
Search for a whole match in a string.
bool match (const std::wstring &in, std::vector< std::wstring > &out) const
Search for a whole match in a string, return sub matches.
Private Types
typedef boost::u32regex regex_type
typedef boost::wsmatch match_type
Private Member Functions
void extract_matches (const match_type &, std::vector< std::wstring > &) const
void extract_matches (const match_type &, std::vector< std::wstring > &, std::vector< int > &) const
Private Attributes
regex_type re
Member Typedef Documentation
typedef boost::wsmatch freeling::regexp::match_type [private]
typedef boost::u32regex freeling::regexp::regex_type [private]
Constructor & Destructor Documentation
freeling::regexp::regexp (const regexp & r)
Copy constructor.
freeling::regexp::regexp (const std::wstring & expr, bool icase = false)
freeling::regexp::~regexp ()
Destructor.
Member Function Documentation
void freeling::regexp::extract_matches (const match_type & , std::vector< std::wstring > &) const [private]
void freeling::regexp::extract_matches (const match_type & , std::vector< std::wstring > & , std::vector< int > &) const [private]
bool freeling::regexp::match (const std::wstring & in) const
Search for a whole match in a string.
bool freeling::regexp::match (const std::wstring & in, std::vector< std::wstring > & out) const
Search for a whole match in a string, return sub matches.
bool freeling::regexp::search (const std::wstring & in, bool continuous = false) const
Search for a partial match in a string.
Referenced by freeling::alternatives::analyze(), freeling::phonetics::apply_rule(), freeling::affixes::ApplyRule(), freeling::word::find_tag_match(), freeling::ukb::init_synset_vector(), freeling::rule_expression::match(), and freeling::phonetics::phonetics().
bool freeling::regexp::search (const std::wstring & in, std::vector< std::wstring > & out, bool continuous = false) const
Search for a partial match in a string, return sub matches.
bool freeling::regexp::search (const std::wstring & in, std::vector< std::wstring > & out, std::vector< int > & pos, bool continuous = false) const
Search for a partial match in a string, return sub matches and positions.
bool freeling::regexp::search (std::wstring::const_iterator i1, std::wstring::const_iterator i2, std::vector< std::wstring > & out, bool continuous = false) const
Search for a partial match in a string, return sub matches.
bool freeling::regexp::search (std::wstring::const_iterator i1, std::wstring::const_iterator i2, std::vector< std::wstring > & out, std::vector< int > & pos, bool continuous = false) const
Search for a partial match in a string, return sub matches and positions.
Member Data Documentation
regex_type freeling::regexp::re [private]
The documentation for this class was generated from the following files:
regexp.h
regexp.cc