FreeLing: freeling::senses Class Reference
freeling::senses Class Reference
Class senses implements a sense annotator.
#include <senses.h>
Public Member Functions
senses (const std::wstring &)
Constructor.
~senses ()
Destructor.
void analyze (sentence &) const
analyze given sentence
Private Attributes
bool duplicate
flag to remember whether analysis are duplicated for each possible sense
semanticDB * semdb
sense information
Detailed Description
Class senses implements a sense annotator.
Constructor & Destructor Documentation
freeling::senses::senses (const std::wstring &)
Constructor.
Create the sense annotator.
References freeling::config_file::add_section(), freeling::config_file::close(), ERROR_CRASH, freeling::config_file::get_content_line(), freeling::config_file::get_section(), freeling::config_file::open(), and TRACE.
freeling::senses::~senses ()
Destructor.
Member Function Documentation
void freeling::senses::analyze (sentence & s) const [virtual]
analyze given sentence
Analyze given sentences.
Implements freeling::processor.
References freeling::analysis::set_prob(), freeling::analysis::set_senses(), and TRACE.
Member Data Documentation
bool freeling::senses::duplicate [private]
flag to remember whether analysis are duplicated for each possible sense
semanticDB* freeling::senses::semdb [private]
sense information
The documentation for this class was generated from the following files:
senses.h
senses.cc