FreeLing: freeling::nec Class Reference
freeling::nec Class Reference
The class nec implements a ML-based NE classificator.
#include <nec.h>
Public Member Functions
nec (const std::wstring &)
Constructor.
~nec ()
Destructor.
void analyze (sentence &) const
analyze given sentence
Private Attributes
const fex * extractor
feature extractor
const classifier * classif
adaboost classifier
std::wstring NPtag
Detailed Description
The class nec implements a ML-based NE classificator.
Constructor & Destructor Documentation
freeling::nec::nec (const std::wstring & necFile)
Constructor.
Create a named entity classification module, loading appropriate files.
References freeling::config_file::add_section(), freeling::config_file::close(), ERROR_CRASH, freeling::config_file::get_content_line(), freeling::config_file::get_section(), freeling::config_file::open(), and TRACE.
freeling::nec::~nec ()
Destructor.
Destructor: delete pointers.
Member Function Documentation
void freeling::nec::analyze (sentence & se) const [virtual]
analyze given sentence
Classify NEs in given sentence.
Implements freeling::processor.
References freeling::example::add_feature(), double2wstring, int2wstring, TRACE, and TRACE_SENTENCE.
Member Data Documentation
const classifier* freeling::nec::classif [private]
adaboost classifier
const fex* freeling::nec::extractor [private]
feature extractor
std::wstring freeling::nec::NPtag [private]
The documentation for this class was generated from the following files:
nec.h
nec.cc