FreeLing: freeling::punts Class Reference
freeling::punts Class Reference
Class numbers implements a punctuation sign recognizer.
#include <punts.h>
Public Member Functions
punts (const std::wstring &)
Constructor.
virtual ~punts ()
void analyze (sentence &) const
analyze given sentence
Private Attributes
std::wstring tagOthers
Detailed Description
Class numbers implements a punctuation sign recognizer.
Constructor & Destructor Documentation
freeling::punts::punts (const std::wstring & puntFile)
Constructor.
Create a punctuation sign recognizer.
References freeling::database::access_database(), OTHER, and tagOthers.
virtual freeling::punts::~punts () [inline, virtual]
Member Function Documentation
void freeling::punts::analyze (sentence & se) const [virtual]
analyze given sentence
Detect and annotate punctuation signs in given sentence, using given options.
Implements freeling::processor.
References freeling::database::access_database(), freeling::util::RE_has_alphanum, tagOthers, TRACE, and TRACE_SENTENCE.
Referenced by freeling::maco::analyze().
Member Data Documentation
std::wstring freeling::punts::tagOthers [private]
Referenced by analyze(), and punts().
The documentation for this class was generated from the following files:
punts.h
punts.cc