FreeLing: freeling::List Class Reference
freeling::List Class Reference
#include <prefTree.h>
Classes
struct ListRec
struct ListRecBase
struct ListRecData
struct ListRecEnd
Public Member Functions
List ()
ListRecBase * find (const wchar_t c)
void * push (const wchar_t c, const bool wordEnd=false)
virtual ~List ()
Private Attributes
ListRecBase * begin
ListRecBase * end
Constructor & Destructor Documentation
freeling::List::List () [inline]
Referenced by push().
freeling::List::~List () [virtual]
References begin, freeling::List::ListRecBase::next, and freeling::List::ListRecBase::nextList.
Member Function Documentation
List::ListRecBase * freeling::List::find (const wchar_t c) [inline]
References begin, freeling::List::ListRecBase::next, and freeling::List::ListRecBase::symb.
Referenced by freeling::PrefTree::deleteWord(), freeling::PrefTree::findWord(), and push().
void * freeling::List::push (const wchar_t c, const bool wordEnd = false)
References begin, end, find(), List(), freeling::List::ListRecBase::next, freeling::List::ListRecBase::nextList, and prev.
Referenced by freeling::PrefTree::addWord().
Member Data Documentation
ListRecBase* freeling::List::begin [private]
Referenced by find(), push(), and ~List().
ListRecBase * freeling::List::end [private]
Referenced by push().
The documentation for this class was generated from the following files:
prefTree.h
prefTree.cc