FreeLing: freeling::dep_txala Class Reference
freeling::dep_txala Class Reference
dependencyMaker is a class for obtaining a dependency tree from chunks.
#include <dependencies.h>
Public Member Functions
dep_txala (const std::wstring &, const std::wstring &)
constructor
void analyze (sentence &) const
analyze given sentences
Private Member Functions
dep_tree * dependencies (parse_tree::iterator, parse_tree::iterator) const
compute dependency tree
Private Attributes
completer comp
tree completer
depLabeler labeler
dependency labeler
std::wstring start
Detailed Description
dependencyMaker is a class for obtaining a dependency tree from chunks.
this implementation uses two subclasses: completer: to complete the chunk analysis in a full parse tree depLabeler: to set the labels once the class has build a dependency tree
Constructor & Destructor Documentation
freeling::dep_txala::dep_txala (const std::wstring & , const std::wstring &)
constructor
constructor.
Load a dependecy rule file.
Member Function Documentation
void freeling::dep_txala::analyze (sentence & s) const [virtual]
analyze given sentences
Enrich given sentence with a depenceny tree.
PrintTree(ntr.begin(),k,0); // debugging
Implements freeling::dependency_parser.
References freeling::dep_txala_status::active_flags, freeling::tree< T >::begin(), freeling::sentence::clear_processing_status(), comp, freeling::completer::complete(), dependencies(), freeling::sentence::get_parse_tree(), freeling::depLabeler::label(), labeler, freeling::sentence::num_kbest(), freeling::sentence::set_dep_tree(), freeling::sentence::set_parse_tree(), freeling::sentence::set_processing_status(), and start.
dep_tree * freeling::dep_txala::dependencies (parse_tree::iterator tr, parse_tree::iterator link) const [private]
compute dependency tree
Obtain a depencendy tree from a parse tree.
References freeling::tree< T >::hang_child(), freeling::tree< T >::info, freeling::node::set_chunk(), freeling::depnode::set_link(), and WARNING.
Referenced by analyze().
Member Data Documentation
completer freeling::dep_txala::comp [private]
tree completer
Referenced by analyze().
depLabeler freeling::dep_txala::labeler [private]
dependency labeler
Referenced by analyze().
std::wstring freeling::dep_txala::start [private]
Referenced by analyze().
The documentation for this class was generated from the following files:
dependencies.h
dependencies.cc