FreeLing: freeling::bioner Class Reference
freeling::bioner Class Reference
The class bioner implements an AdaBoost-Based NE recognizer.
#include <bioner.h>
Public Member Functions
bioner (const std::wstring &)
Constructor.
~bioner ()
Destructor.
void SetMultiwordAnalysis (sentence::iterator) const
void analyze (sentence &) const
Recognize NEs in given sentence.
Private Attributes
const fex * extractor
feature extractor
const classifier * classif
adaboost classifier
vis_viterbi vit
Viterbi solver.
Detailed Description
The class bioner implements an AdaBoost-Based NE recognizer.
Constructor & Destructor Documentation
freeling::bioner::bioner (const std::wstring & nerFile)
Constructor.
Perform named entity recognition using AdaBoost.
Create a named entity recognition module, loading appropriate files.
References freeling::util::absolute(), freeling::config_file::add_section(), classif, freeling::config_file::close(), ERROR_CRASH, extractor, freeling::nerc_features::functions, freeling::config_file::get_content_line(), freeling::config_file::get_section(), freeling::util::lowercase(), freeling::config_file::open(), and TRACE.
freeling::bioner::~bioner ()
Destructor.
Destructor: deletes created pointers.
References classif, and extractor.
Member Function Documentation
void freeling::bioner::analyze (sentence & se) const [virtual]
Recognize NEs in given sentence.
Reimplemented from freeling::automat< ner_status >.
References freeling::example::add_feature(), freeling::ner_module::BuildMultiword(), classif, freeling::classifier::classify(), freeling::fex::encode_int(), extractor, freeling::vis_viterbi::find_best_path(), freeling::classifier::get_index(), freeling::classifier::get_label(), freeling::classifier::get_nlabels(), int2wstring, freeling::sentence::rebuild_word_index(), TRACE, TRACE_SENTENCE, and vit.
void freeling::bioner::SetMultiwordAnalysis (sentence::iterator) const
Member Data Documentation
const classifier* freeling::bioner::classif [private]
adaboost classifier
Referenced by analyze(), bioner(), and ~bioner().
const fex* freeling::bioner::extractor [private]
feature extractor
Referenced by analyze(), bioner(), and ~bioner().
vis_viterbi freeling::bioner::vit [private]
Viterbi solver.
Referenced by analyze().
The documentation for this class was generated from the following files:
bioner.h
bioner.cc