FreeLing: freeling::classifier Class Reference
freeling::classifier Class Reference
The class classifier is an abstract class that implements a general ML classifier.
#include <classifier.h>
Public Member Functions
classifier (const std::wstring &)
virtual ~classifier ()
virtual int get_nlabels () const
virtual int get_index (const std::wstring &) const
virtual std::wstring get_label (int) const
virtual std::wstring default_class () const
virtual void classify (const example &, double[]) const =0
Classify given example, returning predictions.
Private Attributes
std::vector< std::wstring > labels
std::wstring label_others
Detailed Description
The class classifier is an abstract class that implements a general ML classifier.
Constructor & Destructor Documentation
freeling::classifier::classifier (const std::wstring &)
virtual freeling::classifier::~classifier () [inline, virtual]
Member Function Documentation
virtual void freeling::classifier::classify (const example & , double []) const [pure virtual]
Classify given example, returning predictions.
Implemented in freeling::adaboost, and freeling::svm.
Referenced by freeling::bioner::analyze().
virtual std::wstring freeling::classifier::default_class () const [virtual]
virtual int freeling::classifier::get_index (const std::wstring &) const [virtual]
Referenced by freeling::bioner::analyze().
virtual std::wstring freeling::classifier::get_label (int) const [virtual]
Referenced by freeling::bioner::analyze().
virtual int freeling::classifier::get_nlabels () const [virtual]
Reimplemented in freeling::svm.
Referenced by freeling::bioner::analyze().
Member Data Documentation
std::wstring freeling::classifier::label_others [private]
std::vector<std::wstring> freeling::classifier::labels [private]
The documentation for this class was generated from the following file:
classifier.h