FreeLing: freeling::check_synon Class Reference
freeling::check_synon Class Reference
lemma has given synonym
#include <dep_rules.h>
Public Member Functions
check_synon (semanticDB &, const std::wstring &, const std::wstring &)
check synonyms
bool eval (dep_tree::iterator) const
eval whether a single node matches a condition only called from check if needed.
Private Attributes
semanticDB & semdb
Detailed Description
lemma has given synonym
Constructor & Destructor Documentation
freeling::check_synon::check_synon (semanticDB & , const std::wstring & , const std::wstring &)
check synonyms
Member Function Documentation
bool freeling::check_synon::eval (dep_tree::iterator n) const [virtual]
eval whether a single node matches a condition only called from check if needed.
The abstract class version should never be reached.
Reimplemented from freeling::rule_expression.
References freeling::rule_expression::find_any(), freeling::semanticDB::get_sense_info(), freeling::semanticDB::get_word_senses(), semdb, and freeling::sense_info::words.
Member Data Documentation
semanticDB& freeling::check_synon::semdb [private]
Referenced by eval().
The documentation for this class was generated from the following files:
dep_rules.h
dep_rules.cc