FreeLing: freeling::ner_module Class Reference
freeling::ner_module Class Reference
The class ner is an abstract class that implements a general NE Recognizer.
#include <ner_module.h>
Public Member Functions
ner_module (const std::wstring &)
virtual ~ner_module ()
virtual int ComputeToken (int, sentence::iterator &, sentence &) const
Allow classes under ner to be incomplete automata.
virtual void ResetActions (ner_status *) const
pure virtual function to be provided by the child class .
virtual void StateActions (int, int, int, sentence::const_iterator, ner_status *) const
pure virtual function to be provided by the child class.
virtual void SetMultiwordAnalysis (sentence::iterator, int, const ner_status *) const
Set the appropriate lemma and tag for the new multiword.
bool ValidMultiWord (const word &, ner_status *) const
Perform last minute validation before effectively building multiword.
sentence::iterator BuildMultiword (sentence &, sentence::iterator, sentence::iterator, int, bool &, ner_status *) const
Build a Multiword and sets its analysis.
Protected Attributes
unsigned int Title_length
length beyond which a multiword made of all capitialized words ("WRECKAGE: TITANIC DISAPPEARS IN NORTHERN SEA") will be considered a title and not a proper noun.
unsigned int AllCaps_Title_length
std::wstring NE_tag
Tag to assign to detected NEs.
bool splitNPs
if we want to split NEs, set this to true
Detailed Description
The class ner is an abstract class that implements a general NE Recognizer.
Constructor & Destructor Documentation
freeling::ner_module::ner_module (const std::wstring &)
References freeling::config_file::add_section(), freeling::config_file::close(), ERROR_CRASH, freeling::config_file::get_content_line(), freeling::config_file::get_section(), freeling::config_file::open(), and wstring2int.
virtual freeling::ner_module::~ner_module () [inline, virtual]
Member Function Documentation
sentence::iterator freeling::ner_module::BuildMultiword (sentence & se, sentence::iterator start, sentence::iterator end, int fs, bool & built, ner_status * st) const
Build a Multiword and sets its analysis.
Effectively build multiword, altering sentence.
References TRACE.
Referenced by freeling::bioner::analyze().
int freeling::ner_module::ComputeToken (int , sentence::iterator & , sentence &) const [virtual]
Allow classes under ner to be incomplete automata.
Allow classes under ner_module to be incomplete automata.
Implements freeling::automat< ner_status >.
Reimplemented in freeling::np.
void freeling::ner_module::ResetActions (ner_status *) const [virtual]
pure virtual function to be provided by the child class .
Resets automaton internal variables when a new search is started.
Implements freeling::automat< ner_status >.
Reimplemented in freeling::np.
void freeling::ner_module::SetMultiwordAnalysis (sentence::iterator i, int fstate, const ner_status * st) const [virtual]
Set the appropriate lemma and tag for the new multiword.
Implements freeling::automat< ner_status >.
Reimplemented in freeling::np.
References TRACE.
void freeling::ner_module::StateActions (int , int , int , sentence::const_iterator , ner_status *) const [virtual]
pure virtual function to be provided by the child class.
Performs appropriate internal actions, given origin and destinanation states, token code and word.
Implements freeling::automat< ner_status >.
Reimplemented in freeling::np.
bool freeling::ner_module::ValidMultiWord (const word & w, ner_status * st) const [virtual]
Perform last minute validation before effectively building multiword.
Reimplemented from freeling::automat< ner_status >.
References freeling::word::get_words_mw().
Member Data Documentation
unsigned int freeling::ner_module::AllCaps_Title_length [protected]
std::wstring freeling::ner_module::NE_tag [protected]
Tag to assign to detected NEs.
bool freeling::ner_module::splitNPs [protected]
if we want to split NEs, set this to true
unsigned int freeling::ner_module::Title_length [protected]
length beyond which a multiword made of all capitialized words ("WRECKAGE: TITANIC DISAPPEARS IN NORTHERN SEA") will be considered a title and not a proper noun.
A value of zero deactivates this behaviour.
The documentation for this class was generated from the following files:
ner_module.h
ner_module.cc