FreeLing: freeling::PrefTree Class Reference
freeling::PrefTree Class Reference
#include <prefTree.h>
Public Member Functions
PrefTree ()
~PrefTree ()
void addWord (const wchar_t *word, List::ListRecBase *lr, const wchar_t *data)
List::ListRecBase * findWord (const wchar_t *) const
List::ListRecData * find (const wchar_t *word) const
void deleteWord (const wchar_t *)
Private Attributes
List * root
size_t DELIM_LEN
Constructor & Destructor Documentation
freeling::PrefTree::PrefTree () [inline]
References DELIM_LEN, and root.
freeling::PrefTree::~PrefTree () [inline]
References root.
Member Function Documentation
void freeling::PrefTree::addWord (const wchar_t * word, List::ListRecBase * lr, const wchar_t * data)
References freeling::List::ListRecData::getValue(), freeling::List::push(), and freeling::List::ListRecData::setValue().
void freeling::PrefTree::deleteWord (const wchar_t * word)
References freeling::List::ListRecData::delValue(), freeling::List::find(), and freeling::List::ListRecData::getValue().
List::ListRecData * freeling::PrefTree::find (const wchar_t * word) const
List::ListRecBase * freeling::PrefTree::findWord (const wchar_t * word) const
References freeling::List::find(), and freeling::List::ListRecBase::nextList.
Member Data Documentation
size_t freeling::PrefTree::DELIM_LEN [private]
Referenced by PrefTree().
List* freeling::PrefTree::root [private]
Referenced by PrefTree(), and ~PrefTree().
The documentation for this class was generated from the following files:
prefTree.h
prefTree.cc