FreeLing: freeling::ner Class Reference
freeling::ner Class Reference
Class ner implements a wrapper to transparently create and access a ner_module named entity recognizer.
#include <ner.h>
Public Member Functions
ner (const std::wstring &)
Constructor.
~ner ()
Destructor.
Detailed Description
Class ner implements a wrapper to transparently create and access a ner_module named entity recognizer.
Constructor & Destructor Documentation
freeling::ner::ner (const std::wstring & npFile)
Constructor.
Create the appropriate numbers_module (according to received options), and create a wrapper to access it.
References freeling::config_file::add_section(), freeling::config_file::close(), ERROR_CRASH, freeling::config_file::get_content_line(), freeling::config_file::get_section(), and freeling::config_file::open().
freeling::ner::~ner ()
Destructor.
Do nothing (the pointer is freed by the factory)
The documentation for this class was generated from the following files:
ner.h
ner.cc