FreeLing: freeling::depLabeler Class Reference
freeling::depLabeler Class Reference
depLabeler is class to set labels into a dependency tree
#include <dependencies.h>
Public Member Functions
depLabeler (const std::wstring &)
Constructor. create dependency parser.
~depLabeler ()
Destructor.
void label (dep_tree *) const
Label nodes in a dependency tree. (Initial call)
void label (dep_tree *, dep_tree::iterator) const
Label nodes in a dependency tree. (recursive)
Private Member Functions
rule_expression * build_expression (const std::wstring &) const
Constructor private method: parse conditions and build rule expression.
Private Attributes
std::map< std::wstring,
std::list< ruleLabeler > > rules
std::set< std::wstring > unique
semanticDB * semdb
std::set< std::wstring > wordclasses
Detailed Description
depLabeler is class to set labels into a dependency tree
Constructor & Destructor Documentation
freeling::depLabeler::depLabeler (const std::wstring &)
Constructor. create dependency parser.
Constructor: create dependency parser.
load SEMDB section
References freeling::util::absolute(), freeling::check_and::add(), freeling::config_file::add_section(), freeling::ruleLabeler::ancestorLabel, build_expression(), freeling::config_file::close(), ERROR_CRASH, freeling::config_file::get_content_line(), freeling::config_file::get_line_num(), freeling::config_file::get_section(), freeling::ruleLabeler::label, freeling::ruleLabeler::line, freeling::completer::load_classes(), freeling::config_file::open(), freeling::ruleLabeler::re, rules, semdb, TRACE, unique, and wordclasses.
freeling::depLabeler::~depLabeler ()
Destructor.
Constructor: create dependency parser.
References semdb.
Member Function Documentation
rule_expression * freeling::depLabeler::build_expression (const std::wstring &) const [private]
Constructor private method: parse conditions and build rule expression.
References ERROR_CRASH, freeling::rule_expression::find(), semdb, TRACE, WARNING, and wordclasses.
Referenced by depLabeler().
void freeling::depLabeler::label (dep_tree * dependency) const
Label nodes in a dependency tree. (Initial call)
Label nodes in a depencendy tree.
(Initial call)
References freeling::tree< T >::begin(), and TRACE.
Referenced by freeling::dep_txala::analyze(), and label().
void freeling::depLabeler::label (dep_tree * dependency, dep_tree::iterator ancestor) const
Label nodes in a dependency tree. (recursive)
Label nodes in a depencendy tree.
(recursive)
const string ancestorLabel = d->info.get_dep_result();
References int2wstring, label(), rules, TRACE, and unique.
Member Data Documentation
std::map<std::wstring, std::list<ruleLabeler> > freeling::depLabeler::rules [private]
Referenced by depLabeler(), and label().
semanticDB* freeling::depLabeler::semdb [private]
Referenced by build_expression(), depLabeler(), and ~depLabeler().
std::set<std::wstring> freeling::depLabeler::unique [private]
Referenced by depLabeler(), and label().
std::set<std::wstring> freeling::depLabeler::wordclasses [private]
Referenced by build_expression(), and depLabeler().
The documentation for this class was generated from the following files:
dependencies.h
dependencies.cc