FreeLing: freeling::traces Class Reference
freeling::traces Class Reference
Class traces implements trace and error handling utilities.
#include <traces.h>
Static Public Member Functions
static void error_crash (const std::wstring &, const std::wstring &, unsigned long)
static trace methods definition. Inlined for efficiency
static void warning (const std::wstring &, const std::wstring &, unsigned long)
static void trace (int, const std::wstring &, const std::wstring &, unsigned long)
static void trace_word (int lv, const word &, const std::wstring &, unsigned long)
static void trace_word_list (int, const std::list< word > &, const std::wstring &, unsigned long)
static void trace_sentence (int, const sentence &, const std::wstring &, unsigned long)
static void trace_sentence_list (int, const std::list< sentence > &, const std::wstring &, unsigned long)
Static Public Attributes
static int TraceLevel = 0
Static data members.
static unsigned long TraceModule = 0x0000000
Detailed Description
Class traces implements trace and error handling utilities.
Member Function Documentation
void freeling::traces::error_crash (const std::wstring & msg, const std::wstring & modname, unsigned long modcode) [inline, static]
static trace methods definition. Inlined for efficiency
void freeling::traces::trace (int lv, const std::wstring & msg, const std::wstring & modname, unsigned long modcode) [inline, static]
References TraceLevel, and TraceModule.
Referenced by trace_sentence().
void freeling::traces::trace_sentence (int lv, const sentence & s, const std::wstring & modname, unsigned long modcode) [inline, static]
References trace(), trace_word(), TraceLevel, and TraceModule.
Referenced by trace_sentence_list().
void freeling::traces::trace_sentence_list (int lv, const std::list< sentence > & ls, const std::wstring & modname, unsigned long modcode) [inline, static]
References trace_sentence(), TraceLevel, and TraceModule.
void freeling::traces::trace_word (int lv, const word & wd, const std::wstring & modname, unsigned long modcode) [inline, static]
References freeling::word::get_form(), freeling::word::get_span_finish(), freeling::word::get_span_start(), freeling::word::get_words_mw(), freeling::word::is_multiword(), freeling::word::selected_begin(), freeling::word::selected_end(), TraceLevel, TraceModule, freeling::word::unselected_begin(), and freeling::word::unselected_end().
Referenced by trace_sentence(), and trace_word_list().
void freeling::traces::trace_word_list (int lv, const std::list< word > & wl, const std::wstring & modname, unsigned long modcode) [inline, static]
References trace_word(), TraceLevel, and TraceModule.
void freeling::traces::warning (const std::wstring & msg, const std::wstring & modname, unsigned long modcode) [inline, static]
Member Data Documentation
int freeling::traces::TraceLevel = 0 [static]
Static data members.
They are global variables, declared here in a separate module so it is linked only once.
Referenced by trace(), trace_sentence(), trace_sentence_list(), trace_word(), and trace_word_list().
unsigned long freeling::traces::TraceModule = 0x0000000 [static]
Referenced by trace(), trace_sentence(), trace_sentence_list(), trace_word(), and trace_word_list().
The documentation for this class was generated from the following files:
traces.h
traces.cc