FreeLing: freeling Namespace Reference
freeling Namespace Reference
explicit instantiations of class automat to satisfy compiler
Classes
class regexp
class tree_iterator
Generic iterator, to derive all the others.
class generic_iterator
class generic_const_iterator
class sibling_iterator
sibling iterator: traverse all children of the same node
class const_sibling_iterator
class preorder_iterator
traverse the tree in preorder (parent first, then children)
class const_preorder_iterator
class tree
class accents
The class accents provides a wrapper to transparently create and access an accents_module to handle accentuation for the appropriate language.
class accents_module
The abstract class accents_module generalizes accentuation rules for different languages.
class accents_default
Derived accents_module for null accentuation (eg english).
class accents_es
Derived accents_module for Spanish accentuation.
class accents_gl
Derived accents_module for Galician accentuation.
class aligner
class alternatives
Class alternatives suggests words that are orthogrphically/phonetically similar to input word.
class automat_status
Class to store status information.
class automat
Abstract class to implement a Finite-State Automaton which is used by modules recognizing multiwords (dates, numbers, quantities, ...).
class bioner
The class bioner implements an AdaBoost-Based NE recognizer.
class edge
Class edge stores all information in a chart edge.
class cell
Class cell stores all information in a chart cell.
class chart
Class chart contains an array of cells that constitute a chart.
class chart_parser
Class chart_parser implements a chart parser.
class config_file
Class to handle loading a config file for freeling module, with XML-like sections.
class condition
Class condition implements a condition of a CG rule.
class ruleCG
Class rule implements a rule of a CG.
class setCG
class constraint_grammar
Class constraint_grammar implements a pseudo CG, ready to be used from a relax PoS tagger.
class coref
The class coref implements a ML-based coreference classificator.
class mention
Class that contains one definite NP (candidate mention)
class coref_fex
Class for the feature extractor.
class csr_kb
class kb: Store information associated to a knowledge base
class database
Class to wrap a berkeley DB database and unify access.
class dates
The class dates provides a wrapper to transparently create and access a dates_module, a temporal expression recognizer for the appropriate language.
class dates_status
Class to store status information.
class dates_module
The abstract class dates_module generalizes temporal expression recognizer for different languages.
class dates_default
The derived class dates_default implements a default date/time recognizer (only simple patterns are recognized).
class dates_es
The derived class dates_es implements a Spanish date/time recognizer.
class dates_ca
The derived class dates_ca implements a Catalan date/time recognizer.
class dates_gl
The derived class dates_gl implements a Galician date/time recognizer.
class dates_pt
The derived class dates_pt implements a Portuguese date/time recognizer.
class dates_en
The derived class dates_en implements an English date/time recognizer.
class dates_ru
The derived class dates_ru implements Russian date/time recognizer.
class matching_attrib
The class matching attrib stores attributes for maching condition.
class matching_condition
The class matching condition stores a condition used in a MATCHING operation of a completer rule.
class completerRule
The class completerRule stores rules used by the completer of parse trees.
class rule_expression
The class rule_expression is an abstract class (interface) for building dynamic restriction on a ruleLabeler which are used by class depLabeler.
class check_and
The following classes are implementations of different constraints.
class check_not
negation
class check_side
side of descendant respect to ancestor (or viceversa)
class check_lemma
find lemma in list of lemmas (separator character is |)
class check_pos
match pos against regexp
class check_category
check category category
class check_wordclass
lemma belongs to a class
class check_tonto
lemma has given top ontology class
class check_semfile
lemma has given WN semantic file
class check_synon
lemma has given synonym
class check_asynon
lemma or any ancestor has given synonym
class ruleLabeler
ruleLabeler is an auxiliary class for the depLabeler
class dep_txala_status
Store parsing status information.
class completer
The class completer implements a parse tree completer, which given a partial parse tree (chunker output), completes the full parse according to some grammar rules.
class depLabeler
depLabeler is class to set labels into a dependency tree
class dep_txala
dependencyMaker is a class for obtaining a dependency tree from chunks.
class dependency_parser
The class dependency_parser is just an abstract class generalizing any dependency parser.
class dictionary
The class dictionary implements dictionary search and suffix analysis for word forms.
class factory
This template is used by numbers, quantities, dates, and ner classes to dinamycally create the appropriate subclass of numbers_module, quantities_module, dates_module, or ner_module (according to received options).
class fex
Class fex implements a feature extractor.
class lex_entry
Content of one lexicon entry.
class fex_lexicon
Feature lexicon.
class fex_status
Store status about extracted features.
class fex_condition
Class fex_condition stores a condition to be checked on the target.
class feature_function
Class feature_function is an abstrac class to enable calling module to define user-custom feature functions.
class fex_rule
Class fex_rule stores a feature extraction rule.
class fex_rulepack
Class fex_rulepack stores a batch of feature rules to be applied to the same kind of targets.
class foma_FSM
class rule
Class rule implements a rule of a grammar.
class grammar
Class grammar implements a CFG, ready to be used from a chart parser.
class trellis
class emission_states
The class emission_states stores the list of states in the HMM that *may* be generating a given word given the two previous words (and their valid tags).
class hmm_tagger
The class hmm_tagger implements the syntactic analyzer and is the main class, which uses all the others.
class idioma
Class "idioma" implements a visible Markov's model that calculates the probability that a text is in a certain language.
class lang_ident
Class "lang_ident" checks a text against all known languages and sorts the results by probability.
class analysis
Class analysis stores a possible reading (lemma, PoS, probability, distance) for a word.
class word
Class word stores all info related to a word: form, list of analysis, list of tokens (if multiword).
class node
Class node stores nodes of a parse_tree Each node in the tree is either a label (intermediate node) or a word (leaf node)
class parse_tree
Class parse tree is used to store the results of parsing.
class depnode
class denode stores nodes of a dependency tree and parse tree <-> deptree relations
class dep_tree
class dep_tree stores a dependency tree
class processor_status
Virtual class to store the processing state of a sentence.
class sentence
Class sentence is just a list of words that someone (the splitter) has validated it as a complete sentence.
class paragraph
Class paragraph is just a list of sentences that someone has validated it as a paragraph.
class document
Class document is a list of paragraphs.
class lexer
Simple RegEx lexer to parse UTF8 grammar files without depending on flex (or the like)
class locutions_status
Class to store status information.
class locutions
Class locutions recognizes multiwords belonging to a list obtained from a configuration file.
class maco
Class maco implements the morphological analyzer, which uses all the specific analyzers: dates, numbers, dictionary, etc.
class maco_options
Class maco_options implements a set of specific options of the morphological analyzer.
class nec
The class nec implements a ML-based NE classificator.
class ner
Class ner implements a wrapper to transparently create and access a ner_module named entity recognizer.
class ner_status
Class to store status information.
class ner_module
The class ner is an abstract class that implements a general NE Recognizer.
class nerc_features
available NERC-specific feature extraction functions.
class np
The class np implements a simple proper noun recognizer.
class numbers
Class numbers implements a wrapper to transparently create and access a numbers_module number recognizer for the appropriate language.
class numbers_status
Class to store status information.
class numbers_module
The abstract class numbers_module generalizes nummeric expression recognizer for different languages.
class numbers_default
The derived class numbers_default implements a default number recognizer (only numbers in digits are recognized).
class numbers_es
The derived class numbers_es implements a Spanish number recognizer.
class numbers_ca
The derived class numbers_ca implements a Catalan number recognizer.
class numbers_gl
The derived class numbers_gl implements a Galician number recognizer.
class numbers_pt
The derived class numbers_pt implements a Portuguese number recognizer.
class numbers_it
The derived class numbers_it implements a Italian number recognizer.
class numbers_en
The derived class numbers_en implements an English number recognizer.
class numbers_ru
The derived class numbers_ru implements an Russian number recognizer.
class numbers_cs
The derived class numbers_cs implements a Czeck number recognizer.
class phd
class ph_rule
Auxiliar class to store a phonetic change rule.
class rule_set
class phonetics
This class is a will calculate the phonetic translation of a word.
class List
class PrefTree
class probabilities
Class probabilities sets lexical probabilities for each PoS tag of each word in a sentence.
class processor
Abstract class to define the common API of any FreeLing processing module.
class punts
Class numbers implements a punctuation sign recognizer.
class quantities
Class quantities implements a wrapper to transparently create and access a quantities_module monetary expressions detector for the appropriate language.
class quantities_status
Class to store status information.
class quantities_module
The abstract class quantities_module generalizes a percentage, ratios, and currency expression recognizer for different languages.
class quantities_default
The derived class quantities_default implements a default quantities recognizer (only percentages are recognized).
class quantities_es
The derived class quantities_es implements a Spanish quantities recognizer.
class quantities_ca
The derived class quantities_ca implements a Catalan quantities recognizer.
class quantities_gl
The derived class quantities_gl implements a Galician quantities recognizer.
class quantities_pt
The derived class quantities_pt implements a Portuguese quantities recognizer.
class quantities_en
The derived class quantities_en implements an English quantities recognizer.
class quantities_ru
The derived class quantities_ru implements a Russian quantities recognizer.
class RE_map_rule
Auxiliary class to store a single RE_map rule.
class RE_map
Class tag_map implements a mapping from a regexps to an associated data string.
class constraint
The class constraint implements a constraint for the relaxation labelling algorithm.
class label
The class label stores all information related to a variable label in the relaxation labelling algorithm.
class problem
The class problem stores the structure of a problem, namely, a vector with a position for each variable to consider, and for each variable, a list of initial weights for each possible label.
class relax
The class relax implements a generic solver for consistent labelling problems, using relaxation labelling algorithm.
class relax_tagger
The class relax_tagger implements a PoS tagger based on relaxation labelling algorithm.
class sense_info
Class sense_info stores several semantic info about a sense.
class posmaprule
Auxiliary class to map FL postags to WN codes.
class semanticDB
Class semanticDB implements a semantic DB interface.
class senses
Class senses implements a sense annotator.
class similarity
This class calculates the similarity between two words.
class splitter
Class splitter implements a sentence splitter, which accumulates lists of words until a sentence is completed, and then returns a list of sentence objects.
class affixes
Class suffixes implements suffixation rules and dictionary search for suffixed word forms.
class sufrule
Class sufrule contains an affixation rule, and is used by class suffixes.
class POS_tagger
The class POS_tagger is just an abstract class generalizing a PoS tagger.
class tagset
The class tagset handles PoS tags long to short conversion and morphosintactic feature decomposition.
class tokenizer
Class tokenizer implements a token splitter, which converts a string into a sequence of word objects, according to a set of tokenization rules read from aconfiguration file.
class traces
Class traces implements trace and error handling utilities.
class ukb
class util
Class util implements some utilities for NLP analyzers: "tolower" for latin alfabets, tags manipulation, wstring2number and viceversa conversions, etc.
class adaboost
Class AdaBoost implement a generic AB learner/classifier, which may be based on any kind of weak rule.
class classifier
The class classifier is an abstract class that implements a general ML classifier.
class dataset
Class dataset stores a set of examples uset to train adaboost models.
class category
Class category is an auxiliar class to store information about the example belonging to a category.
class example
Class example is a vector of real-valued features, each identified by an integer label, plus info about to which classes the example belongs to, and with prediction storage functionalities.
class svm
Class svm implements a bianry SVM classifier.
class vis_viterbi
The class vis_viterbi implements the viterbi algorithm given the weights of different labels, without hidden information.
class wr_params
Class wr_params is a dummy class used to derive the set of parameters of each WR type.
class weak_rule
Class weak_rule is an abstract class generalizing any kind of weak rule that adaboost can use.
class wr_factory
Class wr_factory is a factory enabling to register new types of weak_rules (provided they are derived from weak_rule class below.
class mlDTree_params
Class mlDTree_params stores the set of params for this kind of weak rules.
class dt_node
Class dt_node stores the info in one node of the decision tree.
class mlDTree
Class mlDTree implements a multilabel decision tree that can be used by adaboost as a weak rules.
Typedefs
typedef std::pair
< std::wstring, std::wstring > bigram
The class viterbi stores the two maps for each observation: The delta map stores the maximum probability for each state in that observation, the phi map stores the backpath to maximize the probability.
Enumerations
enum setType { FORM_SET, LEMMA_SET, SENSE_SET, CATEGORY_SET }
auxiliary class to store sets defined in the CG
Functions
void PrintTree (parse_tree::iterator n, int k, int depth)
void PrintDepTree (dep_tree::const_iterator n, int depth)
Variables
const std::wstring TAG_DIVIDER = "|"
compact data in format lema1 pos1a|pos1b|pos1c lema2 pos2a|posb to save memory
const std::wstring LEMMA_DIVIDER = " "
const std::wstring UNOBS_INITIAL_STATE = "0.x"
const std::wstring UNOBS_WORD = "<UNOBSERVED_WORD>"
const std::wstring RE_ROMAN = "^([IVXLCDM]+)$"
const std::wstring RE_DATE_DF = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d)))/)(\\d{1,4}))$"
const std::wstring RE_TIME1_DF = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:min|m)?)?)$"
const std::wstring RE_TIME2_DF = "^(?:((?:[0-5])?(?:\\d))(?:min\\.?|m\\.?))$"
const std::wstring RE_DATE_ES = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre|ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/)(\\d{1,4}))$"
const std::wstring RE_TIME1_ES = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutos|min|m)?)?)$"
const std::wstring RE_TIME2_ES = "^(?:((?:[0-5])?(?:\\d))(?:minutos|min\\.?|m\\.?))$"
const std::wstring RE_DATE_CA = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|gener|febrer|mar|abril|maig|juny|juliol|agost|setembre|octubre|novembre|desembre|gen|feb|mar|abr|mai|jun|jul|ago|set|oct|nov|des)/)(\\d{1,4}))$"
const std::wstring RE_TIME1_CA = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minuts|min|m)?)?)$"
const std::wstring RE_TIME2_CA = "^(?:((?:[0-5])?(?:\\d))(?:minuts|min\\.?|m\\.?))$"
const std::wstring RE_DATE_EN = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/)(\\d{1,4}))$"
const std::wstring RE_TIME1_EN = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutes|min|m)?)?)$"
const std::wstring RE_TIME2_EN = "^(?:((?:[0-5])?(?:\\d))(?:minutes|min\\.?|m\\.?))$"
const std::wstring RE_DATE_GL = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|xaneiro|febreiro|marzo|abril|maio|xuo|xullo|agosto|setembro|outubro|novembro|decembro|xan|feb|mar|abr|mai|xu|xul|ago|set|out|nov|dec)/)(\\d{1,4}))$"
const std::wstring RE_TIME1_GL = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutos|min|m)?)?)$"
const std::wstring RE_TIME2_GL = "^(?:((?:[0-5])?(?:\\d))(?:minutos|min\\.?|m\\.?))$"
const std::wstring RE_DATE_PT = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|janeiro|fevereiro|maro|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro|jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez)/)(\\d{1,4}))$"
const std::wstring RE_TIME1_PT = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutos|min|m)?)?)$"
const std::wstring RE_TIME2_PT = "^(?:((?:[0-5])?(?:\\d))(?:minutos|min\\.?|m\\.?))$"
const std::wstring RE_DATE_RU = "^([0]?[1-9]|[1|2][0-9]|[3][0|1])[./]([0]?[1-9]|[1][0-2])[./]([0-9]{4}|[0-9]{2})$"
const std::wstring RE_TIME_RU = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:\\.?|:)(?:((?:[0-5])?(?:\\d))(?:?|\\.?)?)?)$"
const std::wstring RE_MINUTES_RU = "^(?:((?:[0-5])?(?:\\d))(?:?|\\.?))$"
const std::wstring UNKNOWN_SYMB = "??"
const std::wstring RE_NA = "^(NC|AQ)"
const std::wstring RE_DNP = "^[FWZ]"
const std::wstring RE_CLO = "^[DSC]"
const std::wstring RE_FZ = "^[FZ]"
const std::wstring USER_RE = "^u\\.([0-9]+)=(.+)$"
const std::wstring RE_WNP = "^[NARV]"
Detailed Description
explicit instantiations of class automat to satisfy compiler
MOD_TRACECODE and MOD_TRACENAME are empty.
Class foma_FSM is a wrapper for the FOMA library, for the specific use of getting entries from a dictionary with minimum edit distance to given key.
The class using the trace is expected to set them
Typedef Documentation
typedef std::pair<std::wstring, std::wstring> freeling::bigram
The class viterbi stores the two maps for each observation: The delta map stores the maximum probability for each state in that observation, the phi map stores the backpath to maximize the probability.
An instance of this class is created for each sentence to be tagged, and destroyed when work is finished.
Enumeration Type Documentation
enum freeling::setType
auxiliary class to store sets defined in the CG
Enumerator:
FORM_SET
LEMMA_SET
SENSE_SET
CATEGORY_SET
Function Documentation
void freeling::PrintDepTree (dep_tree::const_iterator n, int depth)
References freeling::word::get_form(), freeling::word::get_lemma(), freeling::word::get_tag(), and last.
void freeling::PrintTree (parse_tree::iterator n, int k, int depth)
References freeling::word::get_form(), freeling::word::get_lemma(), and freeling::word::get_tag().
Variable Documentation
const std::wstring freeling::LEMMA_DIVIDER = " "
Referenced by freeling::dictionary::add_analysis(), freeling::dictionary::compact_data(), and freeling::dictionary::search_form().
const std::wstring freeling::RE_CLO = "^[DSC]"
const std::wstring freeling::RE_DATE_CA = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|gener|febrer|mar|abril|maig|juny|juliol|agost|setembre|octubre|novembre|desembre|gen|feb|mar|abr|mai|jun|jul|ago|set|oct|nov|des)/)(\\d{1,4}))$"
const std::wstring freeling::RE_DATE_DF = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d)))/)(\\d{1,4}))$"
const std::wstring freeling::RE_DATE_EN = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/)(\\d{1,4}))$"
const std::wstring freeling::RE_DATE_ES = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre|ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)/)(\\d{1,4}))$"
const std::wstring freeling::RE_DATE_GL = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|xaneiro|febreiro|marzo|abril|maio|xuo|xullo|agosto|setembro|outubro|novembro|decembro|xan|feb|mar|abr|mai|xu|xul|ago|set|out|nov|dec)/)(\\d{1,4}))$"
const std::wstring freeling::RE_DATE_PT = "^(?:(?:((?:[0-3])?(?:\\d))/)(?:((?:(?:[0-1])?(?:\\d))|janeiro|fevereiro|maro|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro|jan|fev|mar|abr|mai|jun|jul|ago|set|out|nov|dez)/)(\\d{1,4}))$"
const std::wstring freeling::RE_DATE_RU = "^([0]?[1-9]|[1|2][0-9]|[3][0|1])[./]([0]?[1-9]|[1][0-2])[./]([0-9]{4}|[0-9]{2})$"
const std::wstring freeling::RE_DNP = "^[FWZ]"
const std::wstring freeling::RE_FZ = "^[FZ]"
const std::wstring freeling::RE_MINUTES_RU = "^(?:((?:[0-5])?(?:\\d))(?:?|\\.?))$"
const std::wstring freeling::RE_NA = "^(NC|AQ)"
const std::wstring freeling::RE_ROMAN = "^([IVXLCDM]+)$"
const std::wstring freeling::RE_TIME1_CA = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minuts|min|m)?)?)$"
const std::wstring freeling::RE_TIME1_DF = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:min|m)?)?)$"
const std::wstring freeling::RE_TIME1_EN = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutes|min|m)?)?)$"
const std::wstring freeling::RE_TIME1_ES = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutos|min|m)?)?)$"
const std::wstring freeling::RE_TIME1_GL = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutos|min|m)?)?)$"
const std::wstring freeling::RE_TIME1_PT = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:h|:)(?:((?:[0-5])?(?:\\d))(?:minutos|min|m)?)?)$"
const std::wstring freeling::RE_TIME2_CA = "^(?:((?:[0-5])?(?:\\d))(?:minuts|min\\.?|m\\.?))$"
const std::wstring freeling::RE_TIME2_DF = "^(?:((?:[0-5])?(?:\\d))(?:min\\.?|m\\.?))$"
const std::wstring freeling::RE_TIME2_EN = "^(?:((?:[0-5])?(?:\\d))(?:minutes|min\\.?|m\\.?))$"
const std::wstring freeling::RE_TIME2_ES = "^(?:((?:[0-5])?(?:\\d))(?:minutos|min\\.?|m\\.?))$"
const std::wstring freeling::RE_TIME2_GL = "^(?:((?:[0-5])?(?:\\d))(?:minutos|min\\.?|m\\.?))$"
const std::wstring freeling::RE_TIME2_PT = "^(?:((?:[0-5])?(?:\\d))(?:minutos|min\\.?|m\\.?))$"
const std::wstring freeling::RE_TIME_RU = "^(?:((?:(?:[0-1])?(?:\\d))|(?:2(?:[0-4])))(?:\\.?|:)(?:((?:[0-5])?(?:\\d))(?:?|\\.?)?)?)$"
const std::wstring freeling::RE_WNP = "^[NARV]"
const std::wstring freeling::TAG_DIVIDER = "|"
compact data in format lema1 pos1a|pos1b|pos1c lema2 pos2a|posb to save memory
auxiliary to compact_data
Referenced by freeling::dictionary::add_analysis(), freeling::dictionary::compact_data(), and freeling::dictionary::search_form().
const std::wstring freeling::UNKNOWN_SYMB = "??"
const std::wstring freeling::UNOBS_INITIAL_STATE = "0.x"
Referenced by freeling::hmm_tagger::hmm_tagger().
const std::wstring freeling::UNOBS_WORD = "<UNOBSERVED_WORD>"
Referenced by freeling::hmm_tagger::hmm_tagger().
const std::wstring freeling::USER_RE = "^u\\.([0-9]+)=(.+)$"