FreeLing: freeling::List::ListRecData Struct Reference
freeling::List::ListRecData Struct Reference
#include <prefTree.h>
Public Member Functions
ListRecData ()
ListRecData (wchar_t c)
~ListRecData ()
void setValue (const wchar_t *data)
void delValue ()
const wchar_t * getValue ()
Public Attributes
const wchar_t * value
Constructor & Destructor Documentation
freeling::List::ListRecData::ListRecData () [inline]
freeling::List::ListRecData::ListRecData (wchar_t c) [inline]
freeling::List::ListRecData::~ListRecData () [inline]
References value.
Member Function Documentation
void freeling::List::ListRecData::delValue () [inline]
References value.
Referenced by freeling::PrefTree::deleteWord().
const wchar_t* freeling::List::ListRecData::getValue () [inline]
References value.
Referenced by freeling::database::access_database(), freeling::PrefTree::addWord(), and freeling::PrefTree::deleteWord().
void freeling::List::ListRecData::setValue (const wchar_t * data)
References value.
Referenced by freeling::PrefTree::addWord(), and freeling::database::replace_database().
Member Data Documentation
const wchar_t* freeling::List::ListRecData::value
Referenced by delValue(), getValue(), setValue(), and ~ListRecData().
The documentation for this struct was generated from the following files:
prefTree.h
prefTree.cc